### ISSUE TITLE
Invoice IDs Show NaN Instead of Project Sequence #

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/billing#73]
Invoice IDs are showing NaN instead of correct project sequence # when attempting to e-mail them to users

Sample output from console:

12/2/2019  5:30:48 PM - info: Retrieved data for project OICR_Dockstore
12/2/2019  5:30:48 PM - info: Sending Invoice: OCG-000NaN for project: OICR_Dockstore
12/2/2019  5:30:48 PM - info: Retrieved data for project Seoul_Univ_Kim
12/2/2019  5:30:48 PM - info: Sending Invoice: OCG-000NaN for project: Seoul_Univ_Kim
12/2/2019  5:30:49 PM - info: Retrieved data for project OICR_Yung
12/2/2019  5:30:49 PM - info: Sending Invoice: OCG-000NaN for project: OICR_Yung

**Comment by caravinci** [comment]
The issue seems to have been started by an unhandled authentication issue, due to an expired token.
We've updated prod with a valid token, and the invoices are being generated correctly.
Will observe whether this re-enables the app to autoupdate its token as designed, or whether further intervention is needed.
