### ISSUE TITLE
[Security Vulnerability] Upgrade Multiple Packages

### ISSUE THREAD

**Issue by b-f-chan** [overture-stack/billing#90]
There are several security vulnerabilities to be addressed that have been opened in the past 1-2 months for Enrolment.

Specific Alerts below, please connect the individual PRs to this issue as required:

(1) https://github.com/overture-stack/billing/network/alert/billing-ui/package-lock.json/kind-of/open

(2) https://github.com/overture-stack/billing/network/alert/billing-ui/package-lock.json/acorn/open

(3) https://github.com/overture-stack/billing/network/alert/billing-invoice/yarn.lock/minimist/open

(4) https://github.com/overture-stack/billing/network/alert/billing-ui/package-lock.json/minimist/open

(5) https://github.com/overture-stack/billing/network/alert/invoice-api/yarn.lock/minimist/open

**Comment by caravinci** [comment]
Longwinded write up of some deep changes, for the sake of documentation/posterity: 

As part of this ticket, I've opted to update Billing-UI's React version to the latest stable version (we are still on v15, when v17 has just been made public).
This, to ensure we not only cover a few vulnerable dependencies, but to also bring the app up to speed with current day implementation standards (future proof, for new devs to maintain it after).

The change has been rather smooth, up until dealing with MobX + MobX-React, last of which has gone through a full overhaul, and I wasn't able to maintain the state management (I reckon mostly due to my lack of proper knowledge/understanding of the libraries), not helped by the fact that the rewrite has elicited the disappearance of legacy documentation. No documentation means I have no way of knowing what really is going on in the code, so I can fix it.

Lack of documentation, outdated dependencies having been rewritten entirely, and incompatibility with current + future co-dependencies.
Rather than figure out how to migrate old MobX to their new Hooks-based implementation, and risk other developers having to figure out how the less-than-popular library works, and risk another deprecation; I'm inclined to remove MobX from the app altogether, which granted, is a lot of work but will prove worthy for future maintainability. Using React's own state management is much easier these days with hooks, etc.

Furthermore, less dependencies means less packages to update and code to maintain/refactor.

**Comment by caravinci** [comment]
Rather than addressing individual vulnerable deep dependencies, and risking incompatibility; I've chosen to simply update the whole app. This ensures future proofing, and resolves a few existing bugs in the code.

The PR for this ticket (placeholder for PR, pending tests), updates the whole top level of `billing-ui`'s dependency tree to their latest versions as of today. This ensures all the inner dependencies get updated beyond the vulnerable versions as well, including those that would've been flagged in the next few weeks/months.

- Webpack v5
- React v17
- React-Router v5
- Highcharts v8
- Mobx v6
- AntD v4

Caveat: The only package purposely left in an older version was `History`.
`React-Router@5` doesn't support a history@5 (v6 is in alpha stage still). Will update both as soon as that changes.

**Comment by b-f-chan** [comment]
Do not merge yet, seems the latest deploy has caused some problems with the login.

Sometimes I get a token expired error, other times a bad request error, but takes a few times before I can log in.

Example:

![image.png](https://images.zenhubusercontent.com/5c8bff46913aca2929d7074d/b05150b3-fed8-4cd7-9cb7-98d8880b10a3)

**Comment by caravinci** [comment]
The blank initial load was a config error, resolved already and testable in Lab.
In regards to the token rejection, seems the existing logic in prod doesn't clear session storage whenever a stale token is present, leading to some users getting locked out until they clear it manually. This is obviously not ideal, and since it's been brought up as a blocking issue in this ticket, I'm extending the scope to resolve it.

Will redeploy for testing with a fix for it in a few minutes.

**Comment by b-f-chan** [comment]
Re-rested on lab-billing.cancercollaboratory.org:

- No more login or token issues seen in console (fixed in #109)
- E-mail on Invoices page correctly sent and user is not logged out (fixed in #110)
- All other functionality working properly per normal
- Outstanding $0.00 issue in Object Storage Usage field to be handled in separate ticket

Ready for PR review

**Comment by caravinci** [comment]
Added several comments to the PR (#114), to help document the changes to each file, and the decisions made along the way.
